'use strict';
const $=id=>document.getElementById(id);let entries=[],db,promptEvent;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('minuto-personal',1);r.onupgradeneeded=()=>r.result.createObjectStore('library');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function read(){return new Promise((resolve,reject)=>{const r=db.transaction('library').objectStore('library').get('entries');r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function save(value){return new Promise((resolve,reject)=>{const t=db.transaction('library','readwrite');t.objectStore('library').put(value,'entries');t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
function day(){const d=new Date();if(d.getHours()<6)d.setDate(d.getDate()-1);return {date:d,number:Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/86400000)}}
function index(n,length){let x=(n+0x9e3779b9)|0;x=Math.imul(x^(x>>>16),0x21f0aaad);x=Math.imul(x^(x>>>15),0x735a2d97);return ((x^(x>>>15))>>>0)%length}
function render(){const {date,number}=day();$('date').textContent=date.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});const psalm=index(number,150)+1;$('psalm').textContent=`Ler Salmo ${psalm} no jw.org ↗`;$('psalm').href=`https://www.jw.org/pt/biblioteca/biblia/bi12/livros/salmos/${psalm}/`;if(!entries.length)return;const e=entries[index(number,entries.length)];$('source').textContent=e.book;$('title').textContent=e.title;$('text').textContent=e.text;$('credit').textContent=e.author+(e.chapter?' · '+e.chapter:'');$('count').textContent=`${entries.length} leituras salvas neste aparelho. Disponíveis sem internet.`}
$('file').addEventListener('change',async event=>{const f=event.target.files[0];if(!f)return;try{if(f.size>15000000)throw Error();const data=JSON.parse(await f.text());if(!Array.isArray(data.entries)||!data.entries.length||data.entries.length>10000||!data.entries.every(e=>['title','text','book','author'].every(k=>typeof e[k]==='string')&&e.text.length<100000))throw Error();await save(data.entries);entries=data.entries;render();$('status').textContent='Biblioteca importada. Suas leituras já estão prontas.';if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});}catch{$('status').textContent='Não foi possível importar. Selecione o arquivo minha-biblioteca.json e tente novamente.'}event.target.value=''});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e});
function installed(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone}
$('install').onclick=async()=>{if(promptEvent){await promptEvent.prompt();promptEvent=null;return}$('instructions').textContent=installed()?'O Fides in anima já está instalado neste aparelho.':/iPad|iPhone|iPod/.test(navigator.userAgent)?'No Safari, toque em Compartilhar e depois em Adicionar à Tela de Início. Confirme em Adicionar.':'No Chrome do celular, abra o menu ⋮ e escolha Instalar aplicativo ou Adicionar à tela inicial. A instalação exige que o site esteja publicado em HTTPS.';$('help').showModal()};$('close').onclick=()=>$('help').close();window.addEventListener('appinstalled',()=>{$('install').textContent='Instalado';promptEvent=null});document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});setInterval(render,60000);render();openDB().then(async result=>{db=result;entries=await read();render()}).catch(()=>{$('status').textContent='O navegador bloqueou o armazenamento. Abra no navegador normal para salvar sua biblioteca.'});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{$('status').textContent='A leitura está disponível, mas o modo offline ainda não foi ativado.'});
